from django.conf.urls import patterns, url


urlpatterns = patterns('forum.views',
    url(r'^$',
        'topics_list',
        name="topics-list"),
    url(r'^topic/create/$',
        'topic_create',
        name="topic-create"),
    url(r'^topic/mark-all-read/$',
        'mark_all_topics_read',
        name="mark-all-topics-read"),
    url(r'^topic/(?P<topic_pk>\d+)/(?:([^/]+)/)?comment/$',
        'post_create',
        name="post-create"),
    url(r'^topic/(?P<topic_pk>\d+)/(?:([^/]+)/)?toggle-delete/$',
        'topic_toggle_delete',
        name="topic-toggle-delete"),
    url(r'^topic/(?P<topic_pk>\d+)/(?:([^/]+)/)?last-page/$',
        'posts_list_last_page',
        name="posts-list-last-page"),
    url(r'^topic/(?P<topic_pk>\d+)/(?:([^/]+)/)?$',
        'posts_list',
        name="posts-list"),
    url(r'^post/(?P<post_pk>\d+)/$',
        'post_toggle_delete',
        name="post-toggle-delete"),
    url(r'search/$',
        'posts_search',
        name="posts-search"),
    url(r'user/(?P<user_pk>\d+)/$',
        'user_details',
        name="user-details"),
)
